name: whale
description: A flutter navigation 2.0 router for mobile app
version: 1.1.2
homepage: https://github.com/bebe0612/whale

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter: